name: Docker image CI

on:
  push:
    branches: [ master ]
    paths:
    - 'nodejs/**'
  pull_request:
    branches: [ master ]
    - 'nodejs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Docker Build
      run: docker build -t tvial/crypto-portfolio ./
      
    - name: Docker Push
      run: docker push tvial/crypto-portfolio
